# Cloud Build configuration for BAIC website
# Includes Cloud Logging configuration for GCP triggers

# Logging configuration
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Install dependencies
  - name: 'node:19'
    entrypoint: npm
    args: ['install']
    
  # Build the React app
  - name: 'node:19'
    entrypoint: npm
    args: ['run', 'build']
    
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/baic-website:$COMMIT_SHA', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/baic-website:$COMMIT_SHA']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'baic-website'
      - '--image'
      - 'gcr.io/$PROJECT_ID/baic-website:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/baic-website:$COMMIT_SHA'
